export type ErrorCode =
  | "VALIDATION_ERROR"
  | "TRIP_REQUEST_NOT_FOUND"
  | "TRIP_REQUEST_ALREADY_CANCELED"
  | "HOLIDAY_TRIP_NOT_ALLOWED"
  | "HOLIDAYS_API_UNAVAILABLE"
  | "INTERNAL_SERVER_ERROR"
  | "INVALID_PASSENGER_COUNT"
  | "RETURN_DATE_BEFORE_DEPARTURE"
  | "SAME_ORIGIN_DESTINATION"
  | "TRIP_ALREADY_EXISTS";
